### ISSUE TITLE
missing templates ?

### ISSUE THREAD

**Issue by vinczente** [pinax/pinax-stripe#242]
Am I missing something or are all the templates missing ?
Do I need an extra tool from somewhere ? 

I installed the application, set my tokens and sync the database. When I go to /payments/payment-methods/, it says "TemplateDoesNotExist" pinax/stripe/paymentmethod_list.html 

I am trying to add a credit card to my user

Thank you

**Comment by vinczente** [comment]
Found https://github.com/pinax/pinax-theme-bootstrap ?

Thanks

**Comment by ossanna16** [comment]
Closing this since it seems to be resolved :)

**Comment by mwarkentin** [comment]
@ossanna16 It does seem like something there should be some docs for - I ran into a similar issue and found the same templates after a while of searching.

**Comment by ossanna16** [comment]
@mwarkentin The templates are shipping as part of pinax-theme-bootstrap. @paltman chose not to do a ton of fancy front-end work on purpose but it's all class-based views, which can be easily extended. He talks a little bit about it in this month's Pinax Hangout on pinax-stripe 👉 http://blog.pinaxproject.com/2016/01/27/recap-january-pinax-hangout/ (see last part of the blog post).

**Comment by ossanna16** [comment]
If one of you would like to make a PR for the docs, that would be awesome!

**Comment by mwarkentin** [comment]
I'm still in the middle of actually wiring django-stripe up, don't think I understand the correct usage quite enough to document at this point. :(

**Comment by ossanna16** [comment]
No problem at all!

**Comment by chozabu** [comment]
Ah, I have to create my own templates?
Just ran into (what seems to be) this issue - slightly mislead by http://stackoverflow.com/questions/29008903/setting-up-a-subscription-with-stripe-django-stripe-payments-error-templated

pip installing pinax-theme-bootstrap does not need to fix the issue, nor can I add `pinax-theme-bootstrap` to installed apps

but since I use DRF, feels like it may be better to skip the templates, and set up API for this

just had a look, found https://github.com/iktw/django-rest-framework-stripe - but it looks like it may be dead?
