### ISSUE TITLE
SaaS Guide is empty

### ISSUE THREAD

**Issue by fodra** [pinax/pinax-stripe#329]
On the getting started section of Readthedocs, 

Default Plan

If you are using pinax-stripe for something like a Software-as-a-Service site with subscriptions, then you will want to also set the Stripe ID for a PINAX_STRIPE_DEFAULT_PLAN setting and install middleware. See the SaaS Guide for more details about working with subscriptions.

SaaS Guide doesn't have content.

**Comment by fodra** [comment]
I was hoping documentation would be added vs just removing the links.

**Comment by iMerica** [comment]
I would prefer that too, but I'm not familiar enough with Pinax to add them myself. 

Basically, this provides all the Models that most people will need when working with Stripe and the built-in webhook support is fantastic.  It appears to not be very opinionated on how to use it in an ecommerce application though. This is probably why theres so many plain old functions in the "actions" directory and not many forms or model methods.

Suggestion for new users:
View this tool as a great starting point instead of a complete turn-key solution to Stripe. Fork the repo, use the built-in models and webhook support, create your own forms, views and templates as needed.

**Comment by paltman** [comment]
No, forking would be a very bad idea. 

There are forms and views in this app, and bootstrap templates exist in pinax-theme-bootstrap. Not everyone uses bootstrap which is why they live in the theme and not the app. 

There is turn key example in the stripe starter project.

**Comment by paltman** [comment]
Link to starter project 

https://github.com/pinax/pinax-starter-projects/tree/stripe

**Comment by paltman** [comment]
Also this might be helpful 

https://youtu.be/TD72smkxbLw
