### ISSUE TITLE
Why this over stripe's python api?

### ISSUE THREAD

**Issue by derek-adair** [pinax/pinax-stripe#375]
I am wondering what benefits pinax-stripe has, for a django user, over the vanilla python implementation.  This looks like a *wonderfully* maintained project, however, i'm having trouble convincing myself that its worth including as a dependency over the vanilla api.

What work does this save me?*

*: I am not a pinax user.

**Comment by paltman** [comment]
@derek-adair It really depends on what you are doing.  Two big benefits you have with `pinax-stripe`:

### 1. You have a local cache of all the Stripe data.

This means that when you need to show your user an invoice, or details about their subscription, or purchases, you can just query local models instead of fetching data across an API during the request/response cycle.

### 2. There is built in Webhook handling and processing.

Sure you can build all that code yourself, but why?

**Comment by derek-adair** [comment]
I've actually opted out because... well mostly the stripe api docs are fucking rad.
For what it's worth I will mostly be pulling in aspects of this code base as I need them.  Really dig the generic StripeObject and how you guys handle the caching.  If/when i make my code base public i will absolutely attribute the code i lovingly stole ;)
