### ISSUE TITLE
Pipenv:  jsonfield dependency incompatible with pinax-eventlog  (need to update to jsonfield > 2.0)

### ISSUE THREAD

**Issue by rcludwick** [pinax/pinax-stripe#542]
pipenv gives the following error: 
`Could not find a version that matches jsonfield<2.0.0,>=1.0.3,>=2.0.2`

This can be fixed by updating jsonfield to >2.0.0

#### Steps to Reproduce
pipenv install pinax-eventlog
pipenv install pinax-stripe

#### What were you expecting to happen?
Everything should be installed without a dependency conflict.

#### What actually happened?
The error messaged above.

**Comment by blueyed** [comment]
I think a PR for `setup.py` makes sense then?

**Comment by wahuneke** [comment]
This is giving me trouble too.

A commit (324bef6ebaad9c704c2a4107d2bbd1dc8e690273) by @meshy on Mar 8 2017 specifically sets the requirement to 1.x.  The commit doesnt explain the reason for this.

@meshy - do you remember the reason you set the version requirement to >=1.0.3 and < 2.0.0 ?

**Comment by meshy** [comment]
Hi @wahuneke, sorry for not writing a better commit message.

I made that commit to get CI working again, as it started failing when `jsonfield` 2.0.0 was released. I made a smaller PR to make the version pin more specific so that I could work on an unrelated PR without getting blocked by the CI.

I should have opened an issue like this one to encourage adding compatibility, but it obviously slipped my mind. I'm glad this has been caught. I hope I haven't caused too much inconvenience.

**Comment by blueyed** [comment]
Pinning the upper version does not appear to be necessary, but let's see: https://github.com/pinax/pinax-stripe/pull/545.

**Comment by rcludwick** [comment]
Yeah, I saw the commit to pin jsonfield, and it looked like it was made to
fix unit tests, but nothing ever came after that to update it.

It would be nice to fix this asap, so I can regain the use of my project's
pipfile.lock again.

**Comment by rcludwick** [comment]
And it looks like #545 cleared unit testing.
